### ISSUE TITLE
Create an SQL script to create DB and tables

### ISSUE THREAD

**Issue by prasanna4567** [prasanna4567/Generic_Medicine#12]
Tables

Compositions
ID(pk) | Composition_name | Generic_comp_eq

Medicines
med_id(pk(not used)) | Medicine_name | Manufacturer | Comp_ID(fk)

**Comment by rahul2001dewangan** [comment]
I would like to contribute, can you please assign this issue to me?

**Comment by prasanna4567** [comment]
Sure. All the best @rahul2001dewangan 
Please make sure you update the instructions in ReadMe too.

**Comment by rahul2001dewangan** [comment]
> Sure. All the best @rahul2001dewangan Please make sure you update the instructions in ReadMe too.

do i have to import the medicines from the csv file or it will be user input?

**Comment by prasanna4567** [comment]
#10's fix will take care of the insertion of data into the tables from medicines.csv.
Creating the tables' definitions is good for the scope of this issue.
